// postulacion.js — Formulario de postulación de candidatos
const menuToggle = document.getElementById('menuToggle');
menuToggle?.addEventListener('click', () => document.querySelector('.nav-list')?.classList.toggle('open'));
const btnEnviar=document.getElementById('btnEnviar'), btnLimpiar=document.getElementById('btnLimpiar'), alertBox=document.getElementById('form-alert'), formDiv=document.getElementById('postForm'), confirmDiv=document.getElementById('confirmacion'), cargoSelect=document.getElementById('cargo');
const params=new URLSearchParams(location.search), vacanteSeleccionada=params.get('id_vacante');
const normalizar=(v='')=>String(v).trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function showAlert(msg,type){alertBox.textContent=msg;alertBox.className=`form-alert ${type}`;alertBox.hidden=false;alertBox.scrollIntoView({behavior:'smooth',block:'center'});}
function leerArchivo(input){const file=input.files[0];if(!file)return Promise.resolve(null);if(file.size>5*1024*1024)return Promise.reject(new Error(`El archivo ${file.name} supera el límite de 5 MB.`));return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({nombreArchivo:file.name,tipoArchivo:file.type||'application/octet-stream',archivo:r.result});r.onerror=()=>reject(new Error(`No fue posible leer ${file.name}.`));r.readAsDataURL(file);});}
async function cargarCargos(){try{const r=await fetch('/api/vacantes');if(!r.ok)throw new Error('No fue posible cargar los cargos disponibles.');const activas=(await r.json()).filter(v=>['abierta','activo','activa'].includes(normalizar(v.estado)));cargoSelect.innerHTML='<option value="" disabled selected>Selecciona una opción</option>';activas.sort((a,b)=>Number(a.id_vacante)-Number(b.id_vacante)).forEach(v=>{const o=new Option(`${v.nombre_cargo||v.titulo} — ${v.nombre_sede||'Sede no definida'}`,String(v.id_vacante));o.dataset.cargo=v.nombre_cargo||v.titulo;cargoSelect.add(o);});if(!activas.length)cargoSelect.innerHTML='<option value="" disabled selected>No hay cargos disponibles</option>';if(vacanteSeleccionada&&activas.some(v=>String(v.id_vacante)===vacanteSeleccionada))cargoSelect.value=vacanteSeleccionada;}catch(e){showAlert(`⚠️ ${e.message}`,'error');}}
cargarCargos();
btnEnviar.addEventListener('click',async()=>{const ids=['nombre','cedula','email','telefono','ciudad','fecha_nac'];const values=Object.fromEntries(ids.map(id=>[id,document.getElementById(id).value.trim()]));const cargoId=cargoSelect.value,cargo=cargoSelect.options[cargoSelect.selectedIndex]?.dataset.cargo||'',exp=document.getElementById('experiencia').value;const files=['hoja_vida','cedula_doc','foto'].map(id=>document.getElementById(id).files.length);if(ids.some(id=>!values[id])||!cargoId||!exp){showAlert('⚠️ Por favor completa todos los campos obligatorios.','error');return;}if(files.some(v=>!v)){showAlert('⚠️ Debes adjuntar hoja de vida, cédula y foto.','error');return;}if(!document.getElementById('terminos').checked){showAlert('⚠️ Debes aceptar el tratamiento de datos personales.','error');return;}try{btnEnviar.disabled=true;btnEnviar.textContent='Enviando...';const docs=await Promise.all(['hoja_vida','cedula_doc','foto'].map(id=>leerArchivo(document.getElementById(id))));docs[0].tipoDocumento='HOJA_DE_VIDA';docs[1].tipoDocumento='CEDULA';docs[2].tipoDocumento='FOTO';const r=await fetch('/api/postulaciones',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,cargo,idVacante:Number(cargoId),documentos:docs})});const data=await r.json();if(!r.ok)throw new Error(data.error||'No fue posible registrar la postulación.');const radicadoEl=document.getElementById('radicadoPostulacion');if(radicadoEl)radicadoEl.textContent=`SID-${data.id_postulacion}`;alertBox.hidden=true;formDiv.hidden=true;confirmDiv.hidden=false;confirmDiv.scrollIntoView({behavior:'smooth'});}catch(e){showAlert(`⚠️ ${e.message}`,'error');}finally{btnEnviar.disabled=false;btnEnviar.textContent='Enviar Postulación';}});
btnLimpiar.addEventListener('click',()=>{['nombre','cedula','email','telefono','ciudad','fecha_nac','descripcion'].forEach(id=>document.getElementById(id).value='');cargoSelect.selectedIndex=0;document.getElementById('experiencia').selectedIndex=0;['hoja_vida','cedula_doc','foto'].forEach(id=>document.getElementById(id).value='');document.getElementById('terminos').checked=false;alertBox.hidden=true;});
