import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

describe("SIDOVI PostgreSQL integration", () => {
  const sql = readFileSync(resolve(process.cwd(), "db/Postgres.sql"), "utf8");
  const server = readFileSync(resolve(process.cwd(), "server.js"), "utf8");

  it("links cargo to its sede without removing the existing entities", () => {
    expect(sql).toMatch(/CREATE TABLE recursos_humanos[\s\S]*?id_rrhh\s+integer\s+GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
    expect(sql).toMatch(/CREATE TABLE cargo[\s\S]*?id_sede\s+integer\s+NOT NULL\s+REFERENCES sede\(id_sede\)/);
    expect(sql).toMatch(/CREATE INDEX idx_cargo_id_sede ON cargo\(id_sede\)/);
    for (const table of ["usuario", "aspirante", "vacante", "postulacion", "documento", "entrevista", "notificacion"]) {
      expect(sql).toContain(`CREATE TABLE ${table}`);
    }
  });

  it("keeps both reporting views available for Recursos Humanos queries", () => {
    expect(sql).toContain("CREATE VIEW vista_historial_aspirante AS");
    expect(sql).toContain("CREATE VIEW vista_estadistica_postulaciones AS");
    expect(server).toContain("FROM vista_estadistica_postulaciones");
    expect(server).toContain("FROM vista_historial_aspirante");
  });

  it("supports local IntelliJ variables and a PostgreSQL connection URL", () => {
    expect(server).toContain("process.env.DATABASE_URL");
    expect(server).toContain("process.env.DB_HOST");
    expect(server).toContain("process.env.DB_PASSWORD");
    expect(server).toContain("process.env.PGSSL");
  });

  it("filters the dashboard using the vacancy site and allows both internal roles", () => {
    expect(server).toContain("WHERE v.id_sede = $1");
    expect(server).toContain("requireRoles('RRHH', 'Gerente')");
  });
});
