-- Migración no destructiva para sedes, cargos y vacantes de SIDOVI.
-- Ejecutar una sola vez conectado a la base configurada en .env.

CREATE TABLE IF NOT EXISTS sede (
    id_sede integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_sede varchar(80) NOT NULL UNIQUE,
    activa boolean NOT NULL DEFAULT true,
    creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cargo (
    id_cargo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cargo varchar(100) NOT NULL,
    descripcion_cargo text NOT NULL DEFAULT '',
    turnos varchar(120) NOT NULL DEFAULT '',
    id_sede integer NOT NULL REFERENCES sede(id_sede) ON UPDATE CASCADE ON DELETE RESTRICT,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cargo_nombre_sede_uk UNIQUE (nombre_cargo, id_sede)
);

ALTER TABLE vacante ADD COLUMN IF NOT EXISTS id_sede integer;
ALTER TABLE vacante ADD COLUMN IF NOT EXISTS id_cargo integer;

INSERT INTO sede (nombre_sede) VALUES
    ('Tunja'), ('Duitama'), ('Sogamoso'), ('Chiquinquirá'), ('Bogotá')
ON CONFLICT (nombre_sede) DO NOTHING;

-- Las vacantes antiguas se distribuyen de manera estable para no dejarlas sin sede.
WITH sedes_ordenadas AS (
    SELECT id_sede,
           ROW_NUMBER() OVER (
               ORDER BY ARRAY_POSITION(
                   ARRAY['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Bogotá'],
                   nombre_sede
               )
           ) AS posicion
    FROM sede
    WHERE nombre_sede IN ('Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Bogotá')
)
UPDATE vacante v
SET id_sede = s.id_sede
FROM sedes_ordenadas s
WHERE v.id_sede IS NULL
  AND s.posicion = ((v.id_vacante - 1) % 5) + 1;

INSERT INTO cargo (nombre_cargo, descripcion_cargo, turnos, id_sede)
SELECT DISTINCT
    v.titulo,
    COALESCE(v.descripcion, ''),
    COALESCE(v.requisitos, ''),
    v.id_sede
FROM vacante v
WHERE v.titulo IS NOT NULL AND v.id_sede IS NOT NULL
ON CONFLICT (nombre_cargo, id_sede) DO NOTHING;

UPDATE vacante v
SET id_cargo = c.id_cargo
FROM cargo c
WHERE c.nombre_cargo = v.titulo
  AND c.id_sede = v.id_sede
  AND v.id_cargo IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'vacante_id_sede_fkey') THEN
        ALTER TABLE vacante ADD CONSTRAINT vacante_id_sede_fkey
            FOREIGN KEY (id_sede) REFERENCES sede(id_sede)
            ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'vacante_id_cargo_fkey') THEN
        ALTER TABLE vacante ADD CONSTRAINT vacante_id_cargo_fkey
            FOREIGN KEY (id_cargo) REFERENCES cargo(id_cargo)
            ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS vacante_id_sede_idx ON vacante(id_sede);
CREATE INDEX IF NOT EXISTS vacante_id_cargo_idx ON vacante(id_cargo);
CREATE INDEX IF NOT EXISTS cargo_id_sede_idx ON cargo(id_sede);
