BEGIN;

ALTER TABLE aspirante ADD COLUMN IF NOT EXISTS sexo varchar(20);
ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS motivo_rechazo text;
ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS resultado text;
ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS fecha_rechazo date;
ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS fecha_contratacion date;

CREATE TABLE IF NOT EXISTS examen_programado (
  id_examen integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_postulacion integer NOT NULL REFERENCES postulacion(id_postulacion) ON DELETE CASCADE,
  tipos text[] NOT NULL DEFAULT '{}',
  fecha date NOT NULL,
  hora time NOT NULL,
  lugar varchar(160) NOT NULL,
  direccion varchar(240) NOT NULL DEFAULT '',
  observaciones text NOT NULL DEFAULT '',
  estado varchar(30) NOT NULL DEFAULT 'PROGRAMADO',
  documentos_resultado jsonb NOT NULL DEFAULT '[]'::jsonb,
  fecha_recepcion date,
  observaciones_rrhh text NOT NULL DEFAULT '',
  resultado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (resultado IN ('APROBADO','RECHAZADO','PENDIENTE')),
  motivo_rechazo text NOT NULL DEFAULT '',
  fecha_verificacion timestamp,
  programado_por integer REFERENCES usuario(id_usuario) ON DELETE SET NULL,
  verificado_por integer REFERENCES usuario(id_usuario) ON DELETE SET NULL,
  creado_en timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_examen_postulacion ON examen_programado(id_postulacion);

CREATE TABLE IF NOT EXISTS historial_proceso (
  id_historial integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_postulacion integer NOT NULL REFERENCES postulacion(id_postulacion) ON DELETE CASCADE,
  estado_anterior varchar(60),
  estado_nuevo varchar(60) NOT NULL,
  detalle text NOT NULL DEFAULT '',
  usuario_id integer REFERENCES usuario(id_usuario) ON DELETE SET NULL,
  creado_en timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_historial_postulacion ON historial_proceso(id_postulacion, creado_en DESC);

ALTER TABLE contrato ADD COLUMN IF NOT EXISTS fecha_firma_programada date;
ALTER TABLE contrato ADD COLUMN IF NOT EXISTS hora_firma time;
ALTER TABLE contrato ADD COLUMN IF NOT EXISTS lugar_firma varchar(160);
ALTER TABLE contrato ADD COLUMN IF NOT EXISTS direccion_firma varchar(240);
ALTER TABLE contrato ADD COLUMN IF NOT EXISTS responsable_firma integer REFERENCES usuario(id_usuario) ON DELETE SET NULL;

COMMIT;
