-- ============================================================================
-- SIDOVI - Esquema y datos de demostración (PostgreSQL)
-- Compatible con server.js (todos los nombres de tablas, columnas y vistas
-- que consume la API).
--
-- Ejecutar una sola vez conectado a la base SIDOVI:
--   psql -U postgres -d SIDOVI -f db/Postgres.sql
--
-- Contenido: esquema completo + datos demo (sedes, cargos, usuarios con rol,
-- vacantes de seguridad, aspirantes, postulaciones, entrevistas, contratos).
-- ============================================================================

BEGIN;

-- =========================== LIMPIEZA ======================================
-- Se elimina el esquema público para regenerarlo en un solo paso.
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;

SET search_path = public, pg_catalog;

-- =========================== TABLAS ========================================

-- Sede: oficinas de Colviseg (clave por la que se filtran dashboard y vacantes).
CREATE TABLE sede (
    id_sede    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_sede varchar(80) NOT NULL UNIQUE,
    activa     boolean NOT NULL DEFAULT true,
    creado_en  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Cargo: puesto operativo asociado a una sede.
CREATE TABLE cargo (
    id_cargo          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cargo      varchar(100) NOT NULL,
    descripcion_cargo text NOT NULL DEFAULT '',
    turnos            varchar(120) NOT NULL DEFAULT '',
    id_sede           integer NOT NULL REFERENCES sede(id_sede) ON UPDATE CASCADE ON DELETE RESTRICT,
    activo            boolean NOT NULL DEFAULT true,
    creado_en         timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cargo_nombre_sede_uk UNIQUE (nombre_cargo, id_sede)
);
CREATE INDEX idx_cargo_id_sede ON cargo(id_sede);

-- Recursos Humanos: dueño de aspirantes seleccionados (requerido por el flujo
-- de entrevistas y por los fixtures de prueba).
CREATE TABLE recursos_humanos (
    id_rrhh      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rrhh  varchar(120) NOT NULL DEFAULT 'Recursos Humanos',
    activo       boolean NOT NULL DEFAULT true
);

-- Usuario: personal interno (RRHH y Gerente). El login usa nombre_completo,
-- contrasena_hash (bcrypt o texto), rol y activo.
CREATE TABLE usuario (
    id_usuario       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo  varchar(120) NOT NULL,
    correo           varchar(120) NOT NULL UNIQUE,
    contrasena_hash  varchar(200) NOT NULL,
    rol              varchar(50) NOT NULL,
    activo           boolean NOT NULL DEFAULT true
);

-- Aspirante: candidato registrado por el formulario público o por RRHH.
CREATE TABLE aspirante (
    id_aspirante     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento   varchar(20)  NOT NULL DEFAULT 'CC',
    numero_documento varchar(30)  NOT NULL,
    nombre_completo  varchar(160) NOT NULL,
    correo           varchar(120) NOT NULL,
    telefono         varchar(30)  NOT NULL DEFAULT '',
    direccion        varchar(160) NOT NULL DEFAULT '',
    fecha_registro   date NOT NULL DEFAULT CURRENT_DATE,
    activo           boolean NOT NULL DEFAULT true,
    CONSTRAINT aspirante_documento_uk UNIQUE (tipo_documento, numero_documento)
);

-- Vacante: oferta laboral. Posee id_sede, id_cargo y nombre_cargo (caché de
-- lectura para listados sin JOIN, como espera server.js).
CREATE TABLE vacante (
    id_vacante         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo             varchar(160) NOT NULL,
    descripcion        text NOT NULL,
    requisitos         text NOT NULL DEFAULT '',
    fecha_publicacion  date NOT NULL DEFAULT CURRENT_DATE,
    estado             varchar(30) NOT NULL DEFAULT 'ABIERTA',
    id_usuario         integer REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    id_sede            integer REFERENCES sede(id_sede) ON UPDATE CASCADE ON DELETE RESTRICT,
    id_cargo           integer REFERENCES cargo(id_cargo) ON UPDATE CASCADE ON DELETE SET NULL,
    nombre_cargo       varchar(120) NOT NULL DEFAULT ''
);
CREATE INDEX idx_vacante_id_sede ON vacante(id_sede);
CREATE INDEX idx_vacante_id_cargo ON vacante(id_cargo);
CREATE INDEX idx_vacante_estado ON vacante(estado);

-- Postulacion: vínculo aspirante-vacante. El estado se guarda en la columna
-- "estado" (valores normalizados tipo EN_REVISION, ENTREVISTA, APROBADO...).
CREATE TABLE postulacion (
    id_postulacion    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aspirante      integer NOT NULL REFERENCES aspirante(id_aspirante) ON UPDATE CASCADE ON DELETE RESTRICT,
    id_vacante        integer NOT NULL REFERENCES vacante(id_vacante) ON UPDATE CASCADE ON DELETE RESTRICT,
    fecha_postulacion date NOT NULL DEFAULT CURRENT_DATE,
    estado            varchar(50) NOT NULL DEFAULT 'EN_REVISION'
);
CREATE INDEX idx_postulacion_id_aspirante ON postulacion(id_aspirante);
CREATE INDEX idx_postulacion_id_vacante ON postulacion(id_vacante);
CREATE INDEX idx_postulacion_estado ON postulacion(estado);

-- Triggers del flujo (mensaje de notificación y validación de postulación única).
CREATE FUNCTION mensaje_postulacion() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    RAISE NOTICE 'Nueva postulacion registrada';
    RETURN NEW;
END;
$$;

CREATE FUNCTION validar_postulacion_unica() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM postulacion
        WHERE id_aspirante = NEW.id_aspirante
          AND id_vacante = NEW.id_vacante
    ) THEN
        RAISE EXCEPTION 'El aspirante ya se ha postulado a esta vacante';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_postulacion
    AFTER INSERT ON postulacion
    FOR EACH ROW EXECUTE FUNCTION mensaje_postulacion();

CREATE TRIGGER trigger_validar_postulacion
    BEFORE INSERT ON postulacion
    FOR EACH ROW EXECUTE FUNCTION validar_postulacion_unica();

-- Documento: hoja de vida o adjuntos del aspirante.
CREATE TABLE documento (
    id_documento     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_documento varchar(120) NOT NULL DEFAULT 'Documento',
    tipo_documento   varchar(50) NOT NULL DEFAULT 'PDF',
    archivo          text NOT NULL DEFAULT 'pendiente',
    id_aspirante     integer NOT NULL REFERENCES aspirante(id_aspirante) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX idx_documento_id_aspirante ON documento(id_aspirante);

-- Aspirantes seleccionados: candidatos aprobados por RRHH que pasan a
-- entrevista. id_postulacion es UNIQUE para permitir ON CONFLICT id_postulacion.
CREATE TABLE aspirantes_seleccionados (
    id_seleccionado integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_postulacion  integer NOT NULL UNIQUE REFERENCES postulacion(id_postulacion) ON UPDATE CASCADE ON DELETE CASCADE,
    fecha_seleccion date NOT NULL DEFAULT CURRENT_DATE,
    estado          varchar(60) NOT NULL DEFAULT 'SELECCIONADO_EN_PROCESO',
    id_rrhh         integer REFERENCES recursos_humanos(id_rrhh) ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE INDEX idx_seleccionados_id_rrhh ON aspirantes_seleccionados(id_rrhh);

-- Entrevista: agenda de una entrevista para un seleccionado. Conserva el PK
-- id_entrevista (referenciado por evaluacion) y una UNIQUE en id_seleccionado
-- para que cada seleccionado tenga una sola fila.
CREATE TABLE entrevista (
    id_entrevista    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_seleccionado  integer NOT NULL UNIQUE REFERENCES aspirantes_seleccionados(id_seleccionado) ON UPDATE CASCADE ON DELETE CASCADE,
    id_postulacion   integer REFERENCES postulacion(id_postulacion) ON UPDATE CASCADE ON DELETE CASCADE,
    fecha_entrevista date NOT NULL,
    modalidad        varchar(30) NOT NULL DEFAULT 'Presencial',
    estado           varchar(30) NOT NULL DEFAULT 'PROGRAMADA',
    observacion      text NOT NULL DEFAULT '',
    id_gerente       integer REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE INDEX idx_entrevista_id_gerente ON entrevista(id_gerente);

-- Evaluacion: calificación gerencial ligada a una entrevista.
CREATE TABLE evaluacion (
    id_evaluacion  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preguntas      text NOT NULL,
    calificacion   integer NOT NULL DEFAULT 0,
    comentarios    text NOT NULL DEFAULT '',
    id_entrevista  integer NOT NULL REFERENCES entrevista(id_entrevista) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX idx_evaluacion_id_entrevista ON evaluacion(id_entrevista);

-- Evidencia: adjuntos (fotos, credenciales) del proceso de postulación.
CREATE TABLE evidencia (
    id_evidencia    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_evidencia  varchar(50) NOT NULL DEFAULT 'Foto',
    descripcion     text NOT NULL DEFAULT '',
    archivo         text NOT NULL DEFAULT 'pendiente',
    id_postulacion  integer NOT NULL REFERENCES postulacion(id_postulacion) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Contrato: vínculo laboral del postulante aprobado.
CREATE TABLE contrato (
    id_contrato    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_postulacion integer NOT NULL UNIQUE REFERENCES postulacion(id_postulacion) ON UPDATE CASCADE ON DELETE CASCADE,
    fecha_inicio   date NOT NULL,
    fecha_fin      date,
    tipo_contrato  varchar(50) NOT NULL DEFAULT 'Término Fijo',
    salario        numeric(12,2) NOT NULL DEFAULT 1423500,
    estado         varchar(30) NOT NULL DEFAULT 'Borrador',
    observaciones  text NOT NULL DEFAULT '',
    creado_en      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_contrato_estado ON contrato(estado);

-- Notificacion: avisos del proceso (usada por la vista y reportes).
CREATE TABLE notificacion (
    id_notificacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje         text NOT NULL,
    leida           boolean NOT NULL DEFAULT false,
    creado_en       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_usuario      integer REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL
);

-- =========================== VISTAS ========================================

-- Historial de cada aspirante: total de postulaciones y última fecha.
CREATE VIEW vista_historial_aspirante AS
SELECT
    a.id_aspirante,
    a.tipo_documento,
    a.numero_documento,
    a.nombre_completo,
    a.correo,
    a.telefono,
    COUNT(p.id_postulacion)::int AS total_postulaciones,
    MAX(p.fecha_postulacion) AS ultima_postulacion
FROM aspirante a
LEFT JOIN postulacion p ON p.id_aspirante = a.id_aspirante
GROUP BY a.id_aspirante;

-- Estadísticas de postulaciones por mes.
CREATE VIEW vista_estadistica_postulaciones AS
SELECT
    ROW_NUMBER() OVER (ORDER BY DATE_TRUNC('month', fecha_postulacion) DESC)::int AS periodo_id,
    'MES'::varchar AS tipo_periodo,
    DATE_TRUNC('month', fecha_postulacion)::date AS periodo_inicio,
    (DATE_TRUNC('month', fecha_postulacion) + INTERVAL '1 month - 1 day')::date AS periodo_fin,
    COUNT(*)::int AS total_postulaciones
FROM postulacion
GROUP BY DATE_TRUNC('month', fecha_postulacion);

-- =========================== DATOS DEMO ====================================

INSERT INTO sede (nombre_sede) VALUES
    ('Tunja'), ('Duitama'), ('Sogamoso'), ('Chiquinquirá'), ('Bogotá');

INSERT INTO recursos_humanos (nombre_rrhh) VALUES
    ('Recursos Humanos Central'), ('Recursos Humanos Bogotá');

-- Contraseñas demo: "123" (comparadas por bcrypt o por igualdad directa en login).
INSERT INTO usuario (nombre_completo, correo, contrasena_hash, rol, activo) VALUES
    ('Ana Lopez',       'ana1@gmail.com',       '123', 'RRHH',    true),
    ('Juan Perez',      'juan2@gmail.com',      '123', 'RRHH',    true),
    ('Carlos Gomez',    'carlos3@gmail.com',    '123', 'Gerente', true),
    ('Luisa Martinez',  'luisa4@gmail.com',     '123', 'RRHH',    true),
    ('Pedro Ramirez',   'pedro5@gmail.com',     '123', 'RRHH',    true),
    ('Sofia Torres',    'sofia6@gmail.com',     '123', 'Gerente', true);

INSERT INTO cargo (nombre_cargo, descripcion_cargo, turnos, id_sede) VALUES
    ('Guarda de Seguridad',  'Vigilancia y control de acceso en instalaciones de clientes.', 'Diurno | Nocturno', 1),
    ('Supervisor de Seguridad', 'Coordinación de turnos y supervisión del personal operativo.', 'Diurno', 1),
    ('Auxiliar de RRHH',     'Apoyo administrativo en selección, archivo y contratación.',    'Diurno', 1),
    ('Técnico CCTV',         'Instalación, monitoreo y soporte de cámaras y redes IP.',       'Rotativo', 2),
    ('Guarda de Seguridad',  'Vigilancia y control de acceso en instalaciones de clientes.', 'Diurno | Nocturno', 2),
    ('Supervisor de Seguridad', 'Coordinación de turnos y supervisión del personal operativo.', 'Diurno', 3),
    ('Guarda de Seguridad',  'Vigilancia y control de acceso en instalaciones de clientes.', 'Diurno | Nocturno', 3),
    ('Guarda de Seguridad',  'Vigilancia en conjuntos residenciales y zonas comerciales.',    'Diurno | Nocturno', 4),
    ('Guarda de Seguridad',  'Vigilancia corporativa y eventos.',                            'Diurno | Nocturno', 5);

INSERT INTO vacante (titulo, descripcion, requisitos, fecha_publicacion, estado, id_usuario, id_sede, id_cargo, nombre_cargo) VALUES
    ('Guarda de Seguridad',  'Vigilancia y control de acceso en instalaciones de clientes.', 'Curso de vigilancia vigente',      CURRENT_DATE - 30, 'ABIERTA', 1, 1, 1, 'Guarda de Seguridad'),
    ('Supervisor de Seguridad', 'Coordinación de turnos y supervisión del personal operativo.', 'Experiencia en supervisión de seguridad', CURRENT_DATE - 25, 'ABIERTA', 1, 1, 2, 'Supervisor de Seguridad'),
    ('Auxiliar de RRHH',     'Apoyo administrativo en selección, archivo y contratación.',  'Técnico o tecnólogo en gestión humana', CURRENT_DATE - 20, 'ABIERTA', 1, 1, 3, 'Auxiliar de RRHH'),
    ('Técnico CCTV',         'Instalación, monitoreo y soporte de cámaras y redes IP.',     'Certificación técnica CCTV',       CURRENT_DATE - 15, 'ABIERTA', 2, 2, 4, 'Técnico CCTV'),
    ('Guarda de Seguridad',  'Vigilancia en conjunto residencial, turno nocturno.',         'Curso de vigilancia vigente',      CURRENT_DATE - 10, 'ABIERTA', 3, 4, 7, 'Guarda de Seguridad'),
    ('Guarda de Seguridad',  'Vigilancia corporativa en Bogotá.',                            'Curso de vigilancia vigente',      CURRENT_DATE - 5,  'ABIERTA', 5, 5, 9, 'Guarda de Seguridad');

-- Aspirantes demo (los mismos del dataset original renombrados al modelo nuevo).
INSERT INTO aspirante (tipo_documento, numero_documento, nombre_completo, correo, telefono, direccion, fecha_registro) VALUES
    ('CC', '1001', 'Luis Arias',     'luis1@gmail.com',   '300111', 'Dir1',  '2024-01-01'),
    ('CC', '1002', 'Maria Bustos',   'maria2@gmail.com',  '300112', 'Dir2',  '2024-01-02'),
    ('CC', '1003', 'Jose Cano',      'jose3@gmail.com',   '300113', 'Dir3',  '2024-01-03'),
    ('CC', '1004', 'Elena Duran',    'elena4@gmail.com',  '300114', 'Dir4',  '2024-01-04'),
    ('CC', '1005', 'Mario Espitia',  'mario5@gmail.com',  '300115', 'Dir5',  '2024-01-05'),
    ('CC', '1006', 'Rosa Florez',    'rosa6@gmail.com',   '300116', 'Dir6',  '2024-01-06'),
    ('CC', '1007', 'Hugo Garcia',    'hugo7@gmail.com',   '300117', 'Dir7',  '2024-01-07'),
    ('CC', '1008', 'Lina Hernandez', 'lina8@gmail.com',   '300118', 'Dir8',  '2024-01-08'),
    ('CC', '1009', 'Ivan Ibarra',    'ivan9@gmail.com',   '300119', 'Dir9',  '2024-01-09'),
    ('CC', '1010', 'Julia Jimenez',  'julia10@gmail.com', '300120', 'Dir10', '2024-01-10'),
    ('CC', '1011', 'Kevin Lozano',   'kevin11@gmail.com', '300121', 'Dir11', '2024-01-11'),
    ('CC', '1012', 'Laura Mejia',    'laura12@gmail.com', '300122', 'Dir12', '2024-01-12'),
    ('CC', '1013', 'Mateo Navas',    'mateo13@gmail.com', '300123', 'Dir13', '2024-01-13'),
    ('CC', '1014', 'Nora Ocampo',    'nora14@gmail.com',  '300124', 'Dir14', '2024-01-14'),
    ('CC', '1015', 'Oscar Pinto',    'oscar15@gmail.com', '300125', 'Dir15', '2024-01-15'),
    ('CC', '1016', 'Patricia Quintero', 'patricia16@gmail.com', '300126', 'Dir16', '2024-01-16'),
    ('CC', '1017', 'Ricardo Rico',   'ricardo17@gmail.com', '300127', 'Dir17', '2024-01-17'),
    ('CC', '1018', 'Sandra Soto',    'sandra18@gmail.com',  '300128', 'Dir18', '2024-01-18'),
    ('CC', '1019', 'Tomas Tellez',   'tomas19@gmail.com',   '300129', 'Dir19', '2024-01-19'),
    ('CC', '1020', 'Ursula Uribe',   'ursula20@gmail.com',  '300130', 'Dir20', '2024-01-20'),
    ('CC', '1034567345', 'Ana Lopez', 'anaaaa@gmail.com',   '3245867302', 'carrera 12', '2025-06-12');

-- Postulaciones demo. Distribución de estados para poblar dashboard y reportes.
INSERT INTO postulacion (id_aspirante, id_vacante, fecha_postulacion, estado) VALUES
    (1,  1, '2024-03-01', 'EN_REVISION'),
    (2,  2, '2024-03-02', 'EN_REVISION'),
    (3,  3, '2024-03-03', 'EN_REVISION'),
    (4,  4, '2024-03-04', 'ENTREVISTA'),
    (5,  5, '2024-03-05', 'APROBADO'),
    (6,  6, '2024-03-06', 'APROBADO'),
    (7,  1, '2024-03-07', 'RECHAZADO_RRHH'),
    (8,  2, '2024-03-08', 'RECHAZADO_RRHH'),
    (9,  3, '2024-03-09', 'EN_REVISION'),
    (10, 4, '2024-03-10', 'ENTREVISTA'),
    (11, 5, '2024-03-11', 'ENTREVISTA'),
    (12, 6, '2024-03-12', 'APROBADO'),
    (13, 1, '2024-03-13', 'EN_REVISION'),
    (14, 2, '2024-03-14', 'EN_REVISION'),
    (15, 3, '2024-03-15', 'EN_REVISION'),
    (16, 4, '2024-03-16', 'ENTREVISTA'),
    (17, 5, '2024-03-17', 'RECHAZADO'),
    (18, 6, '2024-03-18', 'RECHAZADO'),
    (19, 1, '2024-03-19', 'CONTRATADO'),
    (20, 2, '2024-03-20', 'CONTRATADO'),
    (1,  2, '2026-03-30', 'EN_REVISION'),
    (2,  3, '2026-03-30', 'EN_REVISION');

-- Documentos para los aspirantes.
INSERT INTO documento (nombre_documento, tipo_documento, archivo, id_aspirante)
SELECT 'CV', 'PDF', 'ruta', id_aspirante FROM aspirante;

-- Aspirantes seleccionados y entrevistas para los estados ENTREVISTA/APROBADO.
INSERT INTO aspirantes_seleccionados (id_postulacion, fecha_seleccion, estado, id_rrhh)
SELECT id_postulacion, CURRENT_DATE - 8, 'SELECCIONADO_EN_PROCESO', 1
FROM postulacion
WHERE estado IN ('ENTREVISTA', 'APROBADO');

INSERT INTO entrevista (id_seleccionado, id_postulacion, fecha_entrevista, modalidad, estado, observacion, id_gerente)
SELECT s.id_seleccionado,
       s.id_postulacion,
       CURRENT_DATE - 3,
       'Presencial',
       CASE WHEN p.estado = 'APROBADO' THEN 'REALIZADA' ELSE 'PROGRAMADA' END,
       'Entrevista demo',
       3
FROM aspirantes_seleccionados s
JOIN postulacion p ON p.id_postulacion = s.id_postulacion;

INSERT INTO evaluacion (preguntas, calificacion, comentarios, id_entrevista)
SELECT e.preguntas, e.calificacion, e.comentarios, e.id_entrevista
FROM (
    SELECT 'Evaluación gerencial' AS preguntas, 5 AS calificacion, 'Excelente' AS comentarios, id_entrevista
    FROM entrevista
    WHERE estado = 'REALIZADA'
) e;

-- Evidencias de respaldo para las postulaciones con entrevista o contrato.
INSERT INTO evidencia (tipo_evidencia, descripcion, archivo, id_postulacion)
SELECT 'Foto', 'Evidencia', 'ruta', id_postulacion
FROM postulacion
WHERE estado IN ('ENTREVISTA', 'APROBADO', 'CONTRATADO');

-- Contratos para los postulantes CONTRATADO/APROBADO.
INSERT INTO contrato (id_postulacion, fecha_inicio, fecha_fin, tipo_contrato, salario, estado, observaciones)
SELECT id_postulacion, CURRENT_DATE, NULL, 'Término Fijo', 1423500, 'Activo', ''
FROM postulacion
WHERE estado IN ('CONTRATADO', 'APROBADO')
  AND id_postulacion NOT IN (SELECT id_postulacion FROM contrato);

-- Notificaciones demo.
INSERT INTO notificacion (mensaje, leida, id_usuario) VALUES
    ('Nueva postulación registrada en Guarda de Seguridad', false, 1),
    ('Entrevista programada para mañana', false, 3);

-- Reinicia las secuencias para que los próximos registros no colisionen.
SELECT setval(pg_get_serial_sequence('sede', 'id_sede'), (SELECT MAX(id_sede) FROM sede));
SELECT setval(pg_get_serial_sequence('cargo', 'id_cargo'), (SELECT MAX(id_cargo) FROM cargo));
SELECT setval(pg_get_serial_sequence('recursos_humanos', 'id_rrhh'), (SELECT MAX(id_rrhh) FROM recursos_humanos));
SELECT setval(pg_get_serial_sequence('usuario', 'id_usuario'), (SELECT MAX(id_usuario) FROM usuario));
SELECT setval(pg_get_serial_sequence('aspirante', 'id_aspirante'), (SELECT MAX(id_aspirante) FROM aspirante));
SELECT setval(pg_get_serial_sequence('vacante', 'id_vacante'), (SELECT MAX(id_vacante) FROM vacante));
SELECT setval(pg_get_serial_sequence('postulacion', 'id_postulacion'), (SELECT MAX(id_postulacion) FROM postulacion));
SELECT setval(pg_get_serial_sequence('documento', 'id_documento'), (SELECT MAX(id_documento) FROM documento));
SELECT setval(pg_get_serial_sequence('aspirantes_seleccionados', 'id_seleccionado'), (SELECT MAX(id_seleccionado) FROM aspirantes_seleccionados));
SELECT setval(pg_get_serial_sequence('entrevista', 'id_entrevista'), (SELECT MAX(id_entrevista) FROM entrevista));
SELECT setval(pg_get_serial_sequence('evaluacion', 'id_evaluacion'), (SELECT MAX(id_evaluacion) FROM evaluacion));
SELECT setval(pg_get_serial_sequence('evidencia', 'id_evidencia'), (SELECT MAX(id_evidencia) FROM evidencia));
SELECT setval(pg_get_serial_sequence('contrato', 'id_contrato'), (SELECT MAX(id_contrato) FROM contrato));

COMMIT;