-- Migración no destructiva para contratos laborales.
-- Ejecutar una sola vez sobre la base existente.

CREATE TABLE IF NOT EXISTS contrato (
    id_contrato integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_postulacion integer NOT NULL UNIQUE REFERENCES postulacion(id_postulacion),
    fecha_inicio date NOT NULL,
    fecha_fin date,
    tipo_contrato varchar(50) NOT NULL,
    salario numeric(12,2) NOT NULL,
    estado varchar(30) NOT NULL DEFAULT 'Borrador',
    observaciones text NOT NULL DEFAULT '',
    creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS contrato_estado_idx ON contrato(estado);
