-- Migración no destructiva: alinea la base SIDOVI existente con las columnas
-- y tablas que consume server.js, sin borrar ni reemplazar datos.
-- Puede ejecutarse tantas veces como se necesite (todo es idempotente).
--
--   psql -U postgres -d SIDOVI -f db/003_alinear_esquema.sql

BEGIN;

-- vacante: columnas usadas por POST/PATCH /api/vacantes y listados.
ALTER TABLE vacante ADD COLUMN IF NOT EXISTS titulo varchar(160);
ALTER TABLE vacante ADD COLUMN IF NOT EXISTS requisitos text NOT NULL DEFAULT '';

-- Rejilla: para las vacantes existentes, el "título" visible era nombre_cargo.
UPDATE vacante SET titulo = nombre_cargo WHERE titulo IS NULL OR TRIM(titulo) = '';
UPDATE vacante SET nombre_cargo = titulo WHERE nombre_cargo IS NULL OR TRIM(nombre_cargo) = '';

-- entrevista: columna usada por GET/DELETE /api/postulaciones/:id para
-- localizar la entrevista de una postulación.
ALTER TABLE entrevista ADD COLUMN IF NOT EXISTS id_postulacion integer
    REFERENCES postulacion(id_postulacion) ON UPDATE CASCADE ON DELETE CASCADE;

-- Rejilla: rellenar id_postulacion desde el seleccionado correspondiente.
UPDATE entrevista e
SET id_postulacion = s.id_postulacion
FROM aspirantes_seleccionados s
WHERE s.id_seleccionado = e.id_seleccionado
  AND e.id_postulacion IS NULL;

-- documento: columnas que usa el backend (antes se llamaban nombre_archivo/tipo_archivo).
ALTER TABLE documento ADD COLUMN IF NOT EXISTS nombre_documento varchar(120) NOT NULL DEFAULT 'Documento';
ALTER TABLE documento ADD COLUMN IF NOT EXISTS tipo_documento varchar(50) NOT NULL DEFAULT 'PDF';

-- Rejilla: conservar el valor que ya existía en las columnas viejas.
UPDATE documento SET nombre_documento = nombre_archivo
WHERE (nombre_documento = 'Documento') AND nombre_archivo IS NOT NULL AND TRIM(nombre_archivo) <> '';
UPDATE documento SET tipo_documento = tipo_archivo
WHERE (tipo_documento = 'PDF') AND tipo_archivo IS NOT NULL AND TRIM(tipo_archivo) <> '';

-- evaluacion: tabla completa que todavía no existía.
CREATE TABLE IF NOT EXISTS evaluacion (
    id_evaluacion  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preguntas      text NOT NULL,
    calificacion   integer NOT NULL DEFAULT 0,
    comentarios    text NOT NULL DEFAULT '',
    id_entrevista  integer NOT NULL REFERENCES entrevista(id_entrevista) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_evaluacion_id_entrevista ON evaluacion(id_entrevista);

-- evidencia: tabla de adjuntos del proceso.
CREATE TABLE IF NOT EXISTS evidencia (
    id_evidencia   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_evidencia varchar(50) NOT NULL DEFAULT 'Foto',
    descripcion    text NOT NULL DEFAULT '',
    archivo        text NOT NULL DEFAULT 'pendiente',
    id_postulacion integer NOT NULL REFERENCES postulacion(id_postulacion) ON UPDATE CASCADE ON DELETE CASCADE
);

COMMIT;