BEGIN;

-- Esta migración se ejecuta SOLO si ya se aplicó la antigua 007 de seis tablas.
-- No ejecutar Postgres.sql nuevamente.

ALTER TABLE aspirante ADD COLUMN IF NOT EXISTS sexo varchar(20);
ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS motivo_rechazo text;
ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS resultado text;
ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS fecha_rechazo date;
ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS fecha_contratacion date;

CREATE TABLE IF NOT EXISTS examen_programado (
  id_examen integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_postulacion integer NOT NULL REFERENCES postulacion(id_postulacion) ON DELETE CASCADE,
  tipos text[] NOT NULL DEFAULT '{}',
  fecha date NOT NULL,
  hora time NOT NULL,
  lugar varchar(160) NOT NULL,
  direccion varchar(240) NOT NULL DEFAULT '',
  observaciones text NOT NULL DEFAULT '',
  estado varchar(30) NOT NULL DEFAULT 'PROGRAMADO',
  documentos_resultado jsonb NOT NULL DEFAULT '[]'::jsonb,
  fecha_recepcion date,
  observaciones_rrhh text NOT NULL DEFAULT '',
  resultado varchar(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (resultado IN ('APROBADO','RECHAZADO','PENDIENTE')),
  motivo_rechazo text NOT NULL DEFAULT '',
  fecha_verificacion timestamp,
  programado_por integer REFERENCES usuario(id_usuario) ON DELETE SET NULL,
  verificado_por integer REFERENCES usuario(id_usuario) ON DELETE SET NULL,
  creado_en timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE examen_programado ADD COLUMN IF NOT EXISTS documentos_resultado jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE examen_programado ADD COLUMN IF NOT EXISTS fecha_recepcion date;
ALTER TABLE examen_programado ADD COLUMN IF NOT EXISTS observaciones_rrhh text NOT NULL DEFAULT '';
ALTER TABLE examen_programado ADD COLUMN IF NOT EXISTS resultado varchar(20) NOT NULL DEFAULT 'PENDIENTE';
ALTER TABLE examen_programado ADD COLUMN IF NOT EXISTS motivo_rechazo text NOT NULL DEFAULT '';
ALTER TABLE examen_programado ADD COLUMN IF NOT EXISTS fecha_verificacion timestamp;
ALTER TABLE examen_programado ADD COLUMN IF NOT EXISTS verificado_por integer REFERENCES usuario(id_usuario) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS historial_proceso (
  id_historial integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_postulacion integer NOT NULL REFERENCES postulacion(id_postulacion) ON DELETE CASCADE,
  estado_anterior varchar(60),
  estado_nuevo varchar(60) NOT NULL,
  detalle text NOT NULL DEFAULT '',
  usuario_id integer REFERENCES usuario(id_usuario) ON DELETE SET NULL,
  creado_en timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE contrato ADD COLUMN IF NOT EXISTS fecha_firma_programada date;
ALTER TABLE contrato ADD COLUMN IF NOT EXISTS hora_firma time;
ALTER TABLE contrato ADD COLUMN IF NOT EXISTS lugar_firma varchar(160);
ALTER TABLE contrato ADD COLUMN IF NOT EXISTS direccion_firma varchar(240);
ALTER TABLE contrato ADD COLUMN IF NOT EXISTS responsable_firma integer REFERENCES usuario(id_usuario) ON DELETE SET NULL;

-- Copiar exámenes antiguos solamente si la tabla examen_programado está vacía.
DO $$
BEGIN
  IF to_regclass('public.examen_programado') IS NOT NULL
     AND to_regclass('public.examen_documento') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM examen_programado) THEN
    UPDATE examen_programado ex SET
      documentos_resultado=COALESCE((SELECT jsonb_agg(jsonb_build_object('id',ed.id_examen_documento,'nombreDocumento',ed.nombre_documento,'tipoDocumento',ed.tipo_documento,'archivo',ed.archivo,'recibidoEn',ed.recibido_en,'observaciones',ed.observaciones,'creadoEn',ed.creado_en) ORDER BY ed.id_examen_documento) FROM examen_documento ed WHERE ed.id_examen=ex.id_examen),'[]'::jsonb),
      fecha_recepcion=(SELECT MIN(ed.recibido_en) FROM examen_documento ed WHERE ed.id_examen=ex.id_examen),
      resultado=COALESCE((SELECT ve.resultado FROM verificacion_examen ve WHERE ve.id_examen=ex.id_examen ORDER BY ve.verificado_en DESC LIMIT 1),'PENDIENTE'),
      motivo_rechazo=COALESCE((SELECT ve.motivo_rechazo FROM verificacion_examen ve WHERE ve.id_examen=ex.id_examen ORDER BY ve.verificado_en DESC LIMIT 1),''),
      fecha_verificacion=(SELECT ve.verificado_en FROM verificacion_examen ve WHERE ve.id_examen=ex.id_examen ORDER BY ve.verificado_en DESC LIMIT 1),
      verificado_por=(SELECT ve.verificado_por FROM verificacion_examen ve WHERE ve.id_examen=ex.id_examen ORDER BY ve.verificado_en DESC LIMIT 1);
  END IF;
END $$;

-- Preservar las evaluaciones por criterio dentro del JSON de comentarios.
DO $$
BEGIN
  IF to_regclass('public.evaluacion_criterio') IS NOT NULL THEN
    UPDATE evaluacion ev SET comentarios = jsonb_build_object('comentariosAnteriores', ev.comentarios, 'criterios', COALESCE((SELECT jsonb_agg(jsonb_build_object('criterio',ec.criterio,'puntuacion',ec.puntuacion) ORDER BY ec.id_criterio) FROM evaluacion_criterio ec WHERE ec.id_evaluacion=ev.id_evaluacion),'[]'::jsonb))::text
    WHERE EXISTS (SELECT 1 FROM evaluacion_criterio ec WHERE ec.id_evaluacion=ev.id_evaluacion);
  END IF;
END $$;

-- Copiar la agenda de firma a la tabla contrato existente.
DO $$
BEGIN
  IF to_regclass('public.agenda_firma_contrato') IS NOT NULL THEN
    UPDATE contrato c SET fecha_firma_programada=a.fecha, hora_firma=a.hora, lugar_firma=a.lugar, direccion_firma=a.direccion, responsable_firma=a.responsable, observaciones=CASE WHEN a.observaciones='' THEN c.observaciones ELSE a.observaciones END, estado=CASE WHEN c.estado='Borrador' THEN 'Firma programada' ELSE c.estado END
    FROM agenda_firma_contrato a WHERE a.id_postulacion=c.id_postulacion;
  END IF;
END $$;

-- Eliminar únicamente tablas redundantes, ya que sus datos fueron consolidados.
DROP TABLE IF EXISTS evaluacion_criterio;
DROP TABLE IF EXISTS examen_documento;
DROP TABLE IF EXISTS verificacion_examen;
DROP TABLE IF EXISTS agenda_firma_contrato;

COMMIT;
