BEGIN;

ALTER TABLE entrevista ADD COLUMN IF NOT EXISTS id_postulacion integer REFERENCES postulacion(id_postulacion) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE entrevista ADD COLUMN IF NOT EXISTS hora_entrevista time NOT NULL DEFAULT '09:00';

ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS motivo_rechazo text;
ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS resultado text;
ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS fecha_rechazo date;
ALTER TABLE postulacion ADD COLUMN IF NOT EXISTS fecha_contratacion date;

CREATE TABLE IF NOT EXISTS notificacion (
  id_notificacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mensaje text NOT NULL,
  leida boolean NOT NULL DEFAULT false,
  creado_en timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_usuario integer REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_entrevista_postulacion ON entrevista(id_postulacion);
CREATE INDEX IF NOT EXISTS idx_postulacion_estado ON postulacion(estado);
CREATE INDEX IF NOT EXISTS idx_notificacion_usuario ON notificacion(id_usuario, creado_en DESC);

COMMIT;
